server:
  port: 3333
  
spring:
  profiles:
    active: production
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: maps-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
info:
  app:
    name: Rideforce Map Service
    description: This is the map service for the Rideforce Map.

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
